### ISSUE TITLE
G4 - Currently selected menu needs more noticeable theming

### ISSUE THREAD

**Issue by jpinsent** [ccswbs/hjckrrh#201]
The currently selected menu item on the local nav appears to have a very slight tint increase compared to the other menu items, but it is not very noticeable.

![menu theming](https://cloud.githubusercontent.com/assets/12450480/9662183/5b0e67ce-522c-11e5-82ec-92bfe330ce01.PNG)
FAQ is the current page in the above screenshot.

**Comment by jpinsent** [comment]
Button background is now 242424. Much more visible than before.

![menu theming fixed](https://cloud.githubusercontent.com/assets/12450480/11535328/68406518-98e1-11e5-9c21-78ea303e62d5.PNG)

**Comment by mmafe** [comment]
Thanks @jpinsent -- could you also do a check on the navbar in narrow-responsive mode? Some changes were made there as well, and I'd like a second eye to review. :)

**Comment by jpinsent** [comment]
@mmafe Theming here looks good as well, however, there is a slight inconsistency. In full view, the selected & hovered menu item background is always 242424. In the narrow view, the selected menu item background is 333333 and the hovered menu item is 242424.

![narrow theming compare](https://cloud.githubusercontent.com/assets/12450480/11537655/0767319e-98ec-11e5-89c6-53ba55310e67.png)


![regular theming compare](https://cloud.githubusercontent.com/assets/12450480/11537647/ff84fb64-98eb-11e5-9e2d-9d9b639229f5.png)

**Comment by mmafe** [comment]
End up doing that on purpose since it was getting too difficult to see the active item when everything was vertically stacked, especially when we go 2 levels in. 

If you open one of the dropdown menus, you could have 3 items that all look the same colour -- the one you're focused on, the parent active-trail, and the active item. I figured not too many folks would notice the difference on narrow vs. wide, and we'd get benefits by having a slightly different colour.

But then on the wide screen view, it looked better when the focus was that bright, especially when seen close to the global menu (which shows a consistent focus colour across everything.)

What we could do in future is put together a style guide for the look and feel of the menus as a whole, but it seemed out of scope for this issue. :)

**Comment by jpinsent** [comment]
Sounds good. I still feel like the wide screen view should have its focus coloured differently, since it can end up looking a little bit confusing to sighted users if a menu item is highlighted and another is selected. E.g. Which item in the screenshot below is selected VS which one is hovered over is indistinguishable. Tab focus adds an outline, but hover focus looks identical to the selected menu item.

![menu theming 2](https://cloud.githubusercontent.com/assets/12450480/11538729/3c14ece2-98f1-11e5-85b8-b4c399e75247.png)

This is just a suggestion though, and it is certainly out of scope for this issue. I could create a new low priority enhancement request with this if desired, but either way this issue has been resolved and the menu is fully functional & accessible as is.

**Comment by mmafe** [comment]
It makes for a good suggestion -- plus it'd be really quick to change the menu item on wide (essentially I'd be commenting something out). Let's keep everything here on this issue, I'll make the change and update with a comment when the code is pushed. :)

**Comment by mmafe** [comment]
Found the following styling issues:

Issue 1 - All four production sites are using the "secondary" class on their local navigation. This causes the hover/focus styling to be narrower than the full width of the menu.

Issue 2 - No focus / hover styling for the last item in the menu (anything that only uses classes "last" and "collapsed").

Let's fix these two styling issues before we release this code onto master.

**Comment by mmafe** [comment]
Note: This relates to branch issue201.

Any updates can be done to that branch. https://github.com/ccswbs/hjckrrh/tree/issue201

**Comment by mmatthews** [comment]
@mmafe Jackson and I have determined that the lack of background colour on focused links is not due to the `.last` class in combination with the `.collapsed` class, but is instead because of the lack of a `.leaf` class. Any element with children does not receive the `.leaf` class which is used in the stylesheet to add the background colour.

**Comment by JProxxi** [comment]
Fix has been pushed to the branch.

**Comment by mmafe** [comment]
Still seeing the issue with the ```.collapsed``` class. In this case, it's affecting an item that only has ```.collapsed```, so I would not restrict the styling just to items that have both ```.last``` and ```.collapsed```

![issue201-screenshot-1 0](https://cloud.githubusercontent.com/assets/1927902/14188748/1a6abe12-f758-11e5-9ab9-dc80148a17bc.png)

**Comment by mmafe** [comment]
Issue affecting .last and .collapsed has been fixed with recent push to https://github.com/ccswbs/hjckrrh/pull/333.

**Comment by mmafe** [comment]
This issue appears to have been fixed.
